[package]
name = "tui"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
types.workspace = true
serde.workspace = true

ratatui.workspace = true
crossterm.workspace = true
crossbeam-channel.workspace = true
